//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "children"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub cid: i32,
    pub name: String,
    pub ability: f64,
    pub parent: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Cid,
    Name,
    Ability,
    Parent,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Cid,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AnswerRecord,
    ChildCheck,
    Parent,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Cid => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(Some(255u32)).def(),
            Self::Ability => ColumnType::Double.def(),
            Self::Parent => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AnswerRecord => Entity::has_many(super::answer_record::Entity).into(),
            Self::ChildCheck => Entity::has_many(super::child_check::Entity).into(),
            Self::Parent => Entity::belongs_to(super::parent::Entity)
                .from(Column::Parent)
                .to(super::parent::Column::Pid)
                .into(),
        }
    }
}

impl Related<super::answer_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnswerRecord.def()
    }
}

impl Related<super::child_check::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChildCheck.def()
    }
}

impl Related<super::parent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parent.def()
    }
}

impl Related<super::quizes::Entity> for Entity {
    fn to() -> RelationDef {
        super::answer_record::Relation::Quizes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::answer_record::Relation::Children.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
