//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::ans_records::Entity as AnsRecords;
pub use super::children::Entity as Children;
pub use super::parent::Entity as Parent;
pub use super::quiz::Entity as Quiz;
pub use super::quiz_level::Entity as QuizLevel;
