//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::answer_record::Entity as AnswerRecord;
pub use super::children::Entity as Children;
pub use super::parent::Entity as Parent;
pub use super::quiz_groups::Entity as QuizGroups;
pub use super::quizes::Entity as Quizes;
